baseURL: "https://ngrlcu.github.io" 
title: Luca Nigro
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2

params:
    description: "I am a PhD Student at the University of Milan. I work on Quantum Computing, Variational Quantum Algorithms and Quantum Optimization. My PhD is partially funded by ENI S.p.A. and my supervisor is Prof. Enrico Prati."
    author: Luca Nigro
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "April 2024"
    # themese: "responsive", "simple", "clean", "light", "dark", "blog", "minimalist", "highlight.js", "search"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Luca Nigro
          subtitle: "I am a PhD Student at the University of Milan. I work on Quantum Computing, Variational Quantum Algorithms and Quantum Optimization. My PhD is partially funded by ENI S.p.A. and my supervisor is Prof. Enrico Prati."
          imageUrl: "profile.JPG"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Luca Nigro
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
              
    socialIcons:
        - name: CV
          url: "MyCV.pdf"
        - name: Email
          url: mailto:luca.nigro@unimi.it
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Ys6rJ8gAAAAJ&hl=it
        - name: GitHub
          url: https://github.com/ngrlcu
        - name: LinkedIn
          url: https://www.linkedin.com/in/luca-nigro-quantum/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: false
    label:
      text: "Luca Nigro"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
